vich_uploader:
    db_driver: orm

    mappings:
        categories_image:
           uri_prefix: /uploads/categories
           upload_destination: '%kernel.project_dir%/public/uploads/categories'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       
        plats_image:
           uri_prefix: /uploads/plats
           upload_destination: '%kernel.project_dir%/public/uploads/plats'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
   